---
#
# Tsung Configuration
#
#
#
# Tasks for role tsung
#
# Overview:
#
#
# Dependencies:
#
#
#
- name: create a user tsung
  user: name={{tsung_role_name}}

- name: ssh config dir
  file: path=/home/{{tsung_role_name}}/.ssh mode=700 owner={{tsung_role_name}} group={{tsung_role_name}} state=directory

- name: ssh keys
  template: 
    src=./roles/tsung/templates/id_dsa 
    dest=/home/{{tsung_role_name}}/.ssh/id_dsa 
    owner=tsung 
    group=tsung 
    mode=0600

- name: authorized_keys
  template: 
    src=./roles/tsung/templates/id_dsa.pub 
    dest=/home/{{tsung_role_name}}/.ssh/authorized_keys 
    owner=tsung 
    group=tsung 
    mode=0600

- name: foobar
  template: src=./roles/tsung/templates/foobar dest=/home/{{tsung_role_name}}/foobar owner=tsung group=tsung mode=0600

- name: ssh config
  template: src=./roles/tsung/templates/config dest=/home/{{tsung_role_name}}/.ssh/config owner=tsung group=tsung mode=0600

- name: install system packages for tsung compilation
  apt: pkg={{ item }} state=present
  with_items: tsung_debian_pkgs

- name: clone the github repository
  git: >
    repo=https://github.com/processone/tsung.git dest={{tsung_dest_dir}} version={{tsung_version}}

- name: configure
  shell:
    ./configure
    chdir={{tsung_dest_dir}}
    creates={{tsung_dest_dir}}/config.status

- name: make
  shell:
    /usr/bin/make
    chdir={{tsung_dest_dir}}
    creates={{tsung_dest_dir}}/ebin/tsung.app

- name: make install
  shell:
    /usr/bin/make install
    chdir={{tsung_dest_dir}}
